name: Application Build

on:
  workflow_call:  # Triggered by another workflow

jobs:
  Build:
    name: Build and Test Lambda Function
    runs-on: [self-hosted, lz-internal-dind]
    defaults:
      run:
        working-directory: "."
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (v18.x)
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install project dependencies
        run: npm ci

      - name: Build Lambda function
        run: npm run build  # Ensure you have a build script in your package.json

      - name: Test Lambda (Unit tests)
        run: npm run test:ci:unit  # Ensure this is defined in your package.json

      - name: Install pnpm for CDK dependencies
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"
          cache-dependency-path: "cdk/landing-zone/pnpm-lock.yaml"
          always-auth: true
          registry-url: https://${{ steps.arti-auth.outputs.audience }}/artifactory/api/npm/main-npm/

      - run: pnpm install --frozen-lockfile
      - run: pnpm build:bundle

      - name: Upload Lambda build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-build-artifacts
          path: dist/
          retention-days: 1

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lambda-test-results
          path: test-reports/
          retention-days: 1