name: Application Build

on:
  workflow_call:  # Triggered by another workflow

jobs:
  Build:
    name: Build and Test Lambda Function
    runs-on: [self-hosted, lz-internal-dind]
    defaults:
      run:
        working-directory: "."
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Build Lambda function
      - name: Build Lambda
        run: npm run build  # Ensure you have a build script in your package.json

      # Run unit tests for Lambda
      - name: Test Lambda (Unit tests)
        run: npm run test:ci:unit  # Ensure this is defined in your package.json

      # Install pnpm for CDK dependencies
      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
        with:
          version: 9

      # Install CDK dependencies using pnpm
      - name: Install CDK dependencies
        working-directory: "lib"
        run: pnpm install --frozen-lockfile && pnpm build:bundle

      # Run CDK tests
      - name: Test CDK
        working-directory: "lib"
        run: npm test

      # Upload Lambda build artifacts
      - name: Upload Lambda build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-build-artifacts
          path: dist/
          retention-days: 1

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lambda-test-results
          path: test-reports/
          retention-days: 1