name: Deploy Code

on:
  workflow_run:
    workflows: ["CI/CD Pipeline for Lambda with API Gateway and Load Balancer"]  # Name of the build pipeline
    types:
      - completed  # Trigger deployment when the build pipeline completes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you are using

      - name: Install Dependencies
        run: |
          npm install
          npm install -g aws-cdk  # Install AWS CDK globally
          npm install -g pnpm     # Install pnpm globally

      - name: Deploy with CDK
        run: |
          cdk bootstrap  # Initialize the AWS environment
          cdk deploy --require-approval never  # Deploy the stack without manual approval
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'